site_name: "KustoCon"
site_url: https://kqlcafe.github.io/kustocon/
repo_url: https://github.com/KQLCafe/kustocon


# Navigation menu
nav:
  - Conference: 'index.md'
  - About: 'about.md'
  - Code of Conduct: 'Code of Conduct.md'

extra_css:
    - css/extra.css

# Configuration
repo_url: https://github.com/KQLCafe/kustocon
repo_name: "kustocon"
theme:
  name: material
  language: en
  icon: 
    repo: fontawesome/brands/git-alt
    admonition:
      <type>: octicons/alert-16 # material/alert
#  custom_dir: !ENV [THEME_DIR, "material"]
# Default values, taken from mkdocs_theme.yml
  features:
    # - content.code.annotate
    # - content.tabs.link
    # - header.autohide
    # - navigation.expand
    - navigation.indexes
    - navigation.instant
    #- navigation.sections
    - navigation.tabs
    #- navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    # - toc.integrate
  palette:
    - scheme: default
      primary: black
      accent: orange
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      primary: black
      accent: orange
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  # font:
  #  text: Roboto
  #  code: Roboto Mono
  #favicon: img/favicon.png
  icon:
    logo: logo
docs_dir: docs
# Plugins
plugins:
  - search
  

# Customization
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/KQLCafe/kustocon
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/KqlCafe
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/groups/13066066/

# Markdown Extensions 
markdown_extensions:
markdown_extensions:
  - toc:
    permalink: true
  - tables
  - attr_list
  - meta
  - md_in_html
  - admonition
  - footnotes
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
